### ISSUE TITLE
Cand download

### ISSUE THREAD

**Issue by willou12321** [H1emu/H1DepotDownloader#2]
its saying me this:               Using Steam3 suggested CellID: 81
Download failed to due to an unhandled exception: Config already loaded
Failed to retrieve content server list: L'opération a été annulée.
Got 106 licenses for account!
Got session token!
Got Machine Auth: ssfn7268809805124451818 0 2048 2048
Disconnected from Steam

**Comment by QuentinGruber** [comment]
i don't remember was it fixed ? Like wasn't this just a steam issue ? @willou12321  ( reopen the issue if this is still an issue for you )
